### ISSUE TITLE
''Inserter is already closed' error when tried multiprocessing upstream

### ISSUE THREAD

**Issue by gargantr** [tableau/hyper-api-samples#15] opened 2020-09-17 16:57 UTC
When I used the below function in my tableau datapipeline, which writes pandas data frame to a hyper extract, I received "Inserter is already closed" when writing to hyper extract. Please be noted, I didn't try to do multiprocessing to insert data to hyper extract, I was using in a pure pandas operation functions upstream, but the insertion failed.

```
def parallelize_dataframe(df, func, n_cores=4):
    df_split = np.array_split(df, n_cores)
    pool = Pool(n_cores)
    df = pd.concat(pool.map(func, df_split))
    pool.close()
    pool.join()
    return df 
```

```
def convert_df_to_hyper_file(filename, df, path_to_hyper, columns):
    with HyperProcess(
            Telemetry.DO_NOT_SEND_USAGE_DATA_TO_TABLEAU,
            'Tabloader') as hyper:
        with Connection(endpoint=hyper.endpoint,
                        create_mode=CreateMode.CREATE_AND_REPLACE,
                        database=path_to_hyper) as connection:
            hyper_table = TableDefinition(
                filename,
                columns=columns
            )
            connection.catalog.create_table(hyper_table)

            with Inserter(connection, hyper_table) as inserter:
                for index, row in df.iloc.iterrows():
                    try:
                        inserter.add_row(row)
                    except Exception as e:
                        logging.error(f'an error occured at row {index}:'
                                      f'\n {e}')
                inserter.execute()
```

**Comment by vogelsgesang** [comment] 2020-09-17 17:07
Hi @gargantr,

Reading through the code you shared, I couldn't spot an issue.
Your approach seems sound and I would expect this to work.
The usage of multiprocessing happens outside of the HyperAPI-related calls, so it should not influence us.

Can you maybe share a self-contained repro?
Also: the `hyperd.log` file might contain additional hints at what went wrong...

**Comment by gargantr** [comment] 2020-09-17 17:18
[hyperd.log](https://github.com/tableau/hyper-api-samples/files/5240831/hyperd.log)
The above is the log. 

```
def convert_df_to_tableau_compliant(df):
    if {'calendar_date', 'createdat', 'addedat_date'}.issubset(set(df.columns)):
        df['calendar_date'] = pd.to_datetime(
            df['calendar_date'], infer_datetime_format=True
        )
        df['createdat'] = pd.to_datetime(
            df['createdat'], infer_datetime_format=True
        )
        df['addedat_date'] = pd.to_datetime(
            df['addedat_date'], infer_datetime_format=True
        )

    # Tableau hyper extract null type is different from the pandas n/a
    df = df.fillna('')

    # Tableau hyper string has to be string, not 'object'
    types = df.dtypes
    for col in types.index:
        if types[col] == 'object':
            df[col] = df[col].astype(str)
    return df

columns = create_hyper_extract_columns(df, column_types)
df = parallelize_dataframe(df, convert_df_to_tableau_compliant, 4)
convert_df_to_hyper_file(
                    filename=s3key_prefix,
                    df=df,
                    path_to_hyper=path_to_hyper,
                    columns=columns
                )
```

The `create_hyper_extract_columns` just mapped pandas data types to hyper SQL 's data type.

**Comment by gargantr** [comment] 2020-09-17 17:20
If you don't use the `parallelize_dataframe` function, it would work just fine!

**Comment by vogelsgesang** [comment] 2020-09-17 17:26
Thanks for the `hyperd.log`!
From a first look at it, this seems like a bug in HyperAPI.
I will need some more time to look into it though.

I would recommend you remove the log file from your comment now, as it contains some information (such as your table names/column names). Nothing really critical, but maybe something which you might not want to share publicly...

**Comment by gargantr** [comment] 2020-09-17 17:31
Thanks for the reminder :). I will go ahead a delete the comment above. In case you need to reproduce the bug.

```
def convert_df_to_tableau_compliant(df):
    if {'calendar_date', 'createdat', 'addedat_date'}.issubset(set(df.columns)):
        df['calendar_date'] = pd.to_datetime(
            df['calendar_date'], infer_datetime_format=True
        )
        df['createdat'] = pd.to_datetime(
            df['createdat'], infer_datetime_format=True
        )
        df['addedat_date'] = pd.to_datetime(
            df['addedat_date'], infer_datetime_format=True
        )

    # Tableau hyper extract null type is different from the pandas n/a
    df = df.fillna('')

    # Tableau hyper string has to be string, not 'object'
    types = df.dtypes
    for col in types.index:
        if types[col] == 'object':
            df[col] = df[col].astype(str)
    return df

df = parallelize_dataframe(df, convert_df_to_tableau_compliant, 4)
columns = create_hyper_extract_columns(df, column_types)

convert_df_to_hyper_file(
                    filename=s3key_prefix,
                    df=df,
                    path_to_hyper=path_to_hyper,
                    columns=columns
                )
```

**Comment by gargantr** [comment] 2020-09-17 17:51
I do have one more question. Right now in my pipeline, I am converting a data frame with around 20 columns and 7 mm rows into hyper. It takes around 20-25 mins. Is there any way to increase the speed of the conversion?

**Comment by vogelsgesang** [comment] 2020-09-17 17:58
> Is there any way to increase the speed of the conversion?

This depends a lot on where your bottle neck is.
If what you shared so far (i.e. the "prepare and insert into Hyper" part) is the bottleneck, then I would recommend to look into `pantab` (https://pantab.readthedocs.io/en/latest/)

Pantab offers integration of pandas with HyperAPI.
It provides for more convenience (e.g. proper NULL handling out of the box, proper object->string conversions, etc.) while at the same time providing higher performance than what could ever be achieved using Python.
To do so, pantab uses a native Python extension written in C to interface with Hyper - no way you will beat that performance with a Python-conversion program...

However, the downside of pantab is that it provides slightly less customizability. E.g., pantab does not allow you to write raw SQL queries, which HyperAPI does

**Comment by vogelsgesang** [comment] 2020-09-17 19:08
I am having trouble reproducing this issue...

I managed to execute your code snippet, but I am not able to reproduce the "Inserter is already closed" error message.
Instead, I get:

> AttributeError: '_iLocIndexer' object has no attribute 'iterrows'

for the line

```
for index, row in df.iloc.iterrows():
```

If I replace it by

```
for index, row in df.iterrows():
```

everything works as expected: no error message, the data ends up in the Hyper file.

But maybe my data is shaped differently than yours?
Can you provide me a **self-contained** repro? I.e. a Python file, which I can simply run as-is, without any modifications, and which repoduces the issue?

(If you prefer to continue this discussion in a non-public forum, you can join the DataDev slack space using http://tabsoft.co/JoinTableauDev. Simply search for "vogelsgesang" and you will find me 😃 )

**Comment by vogelsgesang** [comment] 2020-11-18 17:57
@gargantr is this still an issue for you?
Unfortunately, I am still unable to reproduce your issue :/

**Comment by vogelsgesang** [comment] 2021-01-23 15:15
closing.
In case this issue still persists, please re-open

**Closed by vogelsgesang** 2021-01-23 15:15 UTC
